name: delivery_system
description: Hệ thống giao hàng 4 app - Driver, Leader, Restaurant, Admin
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Navigation
  go_router: ^16.2.1
  
  # HTTP & API
  dio: ^5.4.3
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  
  # WebSocket
  socket_io_client: ^3.1.2
  
  # Local Storage
  shared_preferences: ^2.3.3
  
  # UI Components
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  
  # Utils
  intl: ^0.20.2
  uuid: ^4.5.0
  equatable: ^2.0.5
  
  # Map & Location (chỉ chạy mobile)
  geolocator: ^14.0.2
  google_maps_flutter: ^2.9.0
  
  # Permission (mobile only)
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code Generation
  build_runner: ^2.7.0
  retrofit_generator: ^10.0.2
  json_serializable: ^6.11.0

flutter:
  uses-material-design: true
